#----------------------- Makefile variables --------------------------
PROJECT_NAME   = Lidy
VERSION        = 1.2.0
GLOBAL_TARGET  = $(PROJECT_NAME)-$(VERSION)
DESCRIPTION    = A small cross-platform C library for sparse matrices handling
AUTHORS        = Nicolas Lermé
